### ISSUE TITLE
Form redisplay

### ISSUE THREAD

**Issue by cspeer** [imagekit-developer/imagekit-ruby#20]
Hi there,

is there a way to make imagekit work with form redisplays?

Following [these instructions](https://github.com/carrierwaveuploader/carrierwave#making-uploads-work-across-form-redisplays) with imagekit gives me
```
 undefined method `get' for nil:NilClass Did you mean? gem 
```
upon saving (with no validation errors): `@instance.save`

**Comment by imagekitio** [comment]
@cspeer Please try the latest version 1.0.9

**Comment by cspeer** [comment]
Yes! It's working now! Thanks a lot!
