### ISSUE TITLE
CarrierWave Uploader uses tmp file after successfull upload

### ISSUE THREAD

**Issue by cspeer** [imagekit-developer/imagekit-ruby#21]
Hi,

so, I noticed a strange behavior.
Say you create a carrierwave uploader and use imagekit as the storage backend. So you create a new record from a `params` hash and save it to the database. In that case carrierwave will upload the picture to imagekit and afterwards you can perform operations like `record_instance.image.url_with(transformations...)`. No problem.

But, if you would do the exact same thing as before, but this time the record cannot be saved to the database (validation errors), calling `record_instance.image.url_with(transformations...)` will throw an error as it is trying to read the temporary file even though carrierwave uploaded the file to imagekit anyway.

So
```ruby
  instance = SomeModel.new(params.require(:scope).permit(:name, :description, :image))
  instance.save
  instance.image.url_with(transformation: [{ width: 200 }])
```
will only work _if_ `instance.save` passes with no validation errors.

I figure since the file is uploaded to imagekit regardless of the parent model being valid or not, accessing the uploaded file should use the uploaded file and not the temporary file.

**Comment by violetviolinist** [comment]
Hey @cspeer ,
so from what I figure, the `url_with()` doesn't work when you pass invalid params while creating an instance of `SomeModel`. Is that right?

**Comment by cspeer** [comment]
Basically yes. The image however is uploaded to imagekit

**Comment by violetviolinist** [comment]
@cspeer  Can you tell me exactly what kind of validations are you using? I tried reproducing the issue with the `presence: true` validator, and I don't see it behaving the way it should (failing to create the model , or upload the image)

**Comment by cspeer** [comment]
Yes, sorry for the delay. Here are the validations:

```ruby
  validates :tenant_id, :name, :composer, :pro, :ipi, :duration, presence: true
  validates :duration, numericality: { only_integer: true, greater_than: 0 }
  validates :bpm, numericality: { only_integer: true, greater_than: 0, allow_nil: true }
  validates_each :published do |record, attr|
    if record[attr]
      record.errors.add(attr, "Needs licenses") if record.prices.map(&:amount).reject { |p| p.nil? }.empty?
    end
  end

  accepts_nested_attributes_for :prices
```

**Comment by violetviolinist** [comment]
@cspeer 
Can you please try this and let me know if it works?

```
  instance = SomeModel.new(params.require(:scope).permit(:name, :description, :image))
  instance.save
  instance.image.reload.url_with(transformation: [{ width: 200 }])
```

Notice the addition of 'reload' in  `instance.image.reload.url_with(transformation: [{ width: 200 }])` (3rd line)

**Comment by cspeer** [comment]
I tried and got this error:

```
undefined method `reload' for #<SongCoverUploader:0x00007fd7541ded08>
```

**Comment by violetviolinist** [comment]
ohh, I'm sorry my bad.
put the reload after instance like this:

`instance.reload.image.url_with(transformation: [{ width: 200}] )`

**Comment by cspeer** [comment]
hah, yeah that makes sense.
However, the error I now get is:
```
Couldn't find Admin::Song without an ID
```
which makes sense as well since the record has validtion errors and hasn't been saved to the database yet

**Comment by violetviolinist** [comment]
Yeah that makes sense. So I tried the numericality validation as well, and even here the image isn't being uploaded to ImageKit as expected. Can you tell me exactly which validation is failing by inspecting the error object on the instance? So I get a better idea.

**Comment by cspeer** [comment]
Alright, I think I figured it out. In order to check if an image exists we do the following:
```
instance.image.to_s.blank?
```
And after further investigation I figured out that calling `.to_s` triggers the upload mechanism but does not update the uploader object properly so that it would be possible to use `.url_with` with it (it tries to use the tmp file).

So, my next attempt was to use `instance.image?` or `instance.image.present?` to determine whether there is a file present that can be displayed. Turns out that both `.image?` and `.image.present?` both return `true` even though nothing has been uploaded. So invoking `.url_with` still results in an error which makes sense because nothing's been uploaded (still both checks return `true`).

When I ignore the uploader reporting `true` for the file and use CarrierWave's form [redisplay freature](https://github.com/carrierwaveuploader/carrierwave#making-uploads-work-across-form-redisplays), I get the error I desribed in #20

**Comment by cspeer** [comment]
Any updates on this? Unfortunately this makes it really hard to work with if not flat out impossible

**Comment by imagekitio** [comment]
@cspeer Please try the latest version 1.0.9

**Comment by cspeer** [comment]
Yes! It's working now! Thanks a lot!
