### ISSUE TITLE
Active Storage integration in the pipeline?

### ISSUE THREAD

**Issue by lentrup** [imagekit-developer/imagekit-ruby#30]
Hi there, 
Are there any plans on building an [Active Storage](https://edgeguides.rubyonrails.org/active_storage_overview.html) integration for Imagekit?

It would be an amazing feature I think a lot of us would really appreciate. 

E.g.: 
`config.active_storage.service = :imagekit`

**Comment by imagekitio** [comment]
Hi @lentrup, thanks for bringing this up. 

Our technology team is evaluating this.

**Comment by imagekitio** [comment]
Version 2.0.0 has support for ActiveStorage
