### ISSUE TITLE
uninitialized constant ActiveStorage::Downloader (NameError)

### ISSUE THREAD

**Issue by dn-conrad** [imagekit-developer/imagekit-ruby#40]
I've tried this every which way I can but seem to be struggling to get the `imagekitio` gem installed and working correctly. Actually, I've got the gem installed and without configuring it in an initializer, all seems to work fine. From a console I've got access to the gem. The problem seems to pop up when I attempt to configure it in a rails initializer using ActiveStorage as documented. 

I'm running Rails 6.0.4.6 and the imagekitio gem is locked at 2.1.0. Without the initializer, I can access the rails console but as soon as I add the initializer for the imagekitio gem and set `config.service = :activestorage`, I get the mentioned error (uninitialized constant ActiveStorage::Downloader (NameError)). I do not have trouble if I set up the initializer to use carrierwave (`config.service = :carrierwave`). It seems to be specific to ActiveStorage

I'm not ruling out user error on this one - I'm able to get the sample rails apps with active storage running but can't get this to work for me. Is anyone else experiencing this?

**Comment by imagekitio** [comment]
@bishosilwal please look into this.

**Comment by bishosilwal** [comment]
Hi @dn-conrad 
Can you please tell me what you did while using imagekitio gem? Also, can you confirm active storage gem was configured before imagekitio gem?
