### ISSUE TITLE
Lighter version of this SDK

### ISSUE THREAD

**Issue by imagekitio** [imagekit-developer/imagekit-ruby#41]
From support ticket:

> Hi there, we use the imagekit gem for our rails environment, but we do not use carrierwave or active storage and use the gem directly. I noticed that the gem has a hard requirement for carrierwave which causes this large gem to be loaded in our rails app. Is it possible to extract the carrierwave integration to it's own gem so that we can control the dependency better and keep the memory profile low?

**Comment by imagekitio** [comment]
@bishosilwal

**Comment by bishosilwal** [comment]
Imagekit gem supports using gem without any carrier wave or active storage integration. Here is the sample ruby app using gem without them.
please follow [this]( https://github.com/imagekit-samples/quickstart/tree/master/ruby/ruby_app)

**Comment by ekkyou** [comment]
@imagekitio is there a way to remove carriewave as a dependency if it's not used or add as a dev dependency? That happens pretty often with other gem that offers a choice.
