### ISSUE TITLE
expire_seconds has no effect

### ISSUE THREAD

**Issue by cspeer** [imagekit-developer/imagekit-ruby#47]
As mentioned in #45 the option `expire_seconds` does not appear to have any effect.
Generated URLs return an Unauthorized only seconds after they are accessed directly even if I set expire_seconds to 5 minutes or more.

**Comment by imagekitio** [comment]
@cspeer can you please share the URLs to support@imagekit.io?

**Comment by cspeer** [comment]
Expected behaviour
If I set `expire_seconds` to a value x in seconds I expect a generated image URL to be accessable for x seconds.

Actual behaviour
It is not accessable for x seconds. It appears to only be accessable for a few milliseconds to one second.

**Comment by imagekitio** [comment]
@cspeer can you please check this now. It should work.

**Comment by imagekitio** [comment]
Please reopen this issue if its still happening along with minimum code to reproduce it at our end.
