### ISSUE TITLE
Why the dependency on CarrierWave?

### ISSUE THREAD

**Issue by tamoyal** [imagekit-developer/imagekit-ruby#55]
I'm confused about the dependency on Carrier Wave given it's an optional setting. I am looking to use the SDK in a plain ruby environment and would prefer no unnecessary dependencies.

**Comment by imagekitio** [comment]
There is a PR https://github.com/imagekit-developer/imagekit-ruby/pull/54/files related to this. We will review and test this soon.

**Comment by stefanahman** [comment]
@tamoyal they just closed my PR without giving any feedback. We ended up not using the gem/service. I hope you solve your problems in some other way!

**Comment by imagekitio** [comment]
The latest version 2.3.0 has the fix and necessary changes from that closed PR. Please check and open this issue if needed.

**Comment by tamoyal** [comment]
@stefanahman Yea we decided to not move forward with it as well. Thanks for letting me know!

**Comment by cspeer** [comment]
With 2.3.0 I'm seeing the following exception:
``/gems/imagekitio-2.3.0/lib/carrierwave/storage/imagekit_store.rb:8:in `<module:Storage>': uninitialized constant CarrierWave (NameError)```

the app does not use carrierwave. so it looks like it's still dependent on carrierwave somehow?
